server:
  servlet:
    contextPath: /map-exercise
  port: 8080
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/EXERCISE?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect